name: clean_achitecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # state managment
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  # Service locator (di)
  get_it: ^7.2.0
  # Remote ApI
  http: ^0.13.4
  # Value equality
  equatable: ^2.0.3
  # Functional programming
  dartz: ^0.10.1
  # check internet connection
  internet_connection_checker: ^0.0.1+4
  # local cash
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
